### ISSUE TITLE
No "insert_patches_lex" function

### ISSUE THREAD

**Issue by scao7** [ashkan-abbasi66/NWSR#1]
I tried to run the code but it says Un recognized function or variable 'insert_patches_lex'.  I have checked all the files and I couldn't find the definition of the function. Do you forget to upload this function file?

**Comment by scao7** [comment]
Just check the comment's in the Get_patches_2_lex.m 

%--------------------------------------------
% USAGE:
% % % This example shows the following functions are equivalent:
% % % extract_patches_lex <=> Get_patches_2_lex
% % % insert_patches_lex <=> insert_patches_Get_patches_2_lex
% % %
% % im=im2double(imread('cameraman.tif'));
% % [R,C]=size(im);
% % ps=[8 8];
% % step=[1 1];
% % tic
% % %
% % % X=extract_patches_lex(im,ps,step);
% % X=Get_patches_2_lex(im,ps);
% % %
% % % im2=insert_patches_lex(X,R,C,ps,step);
% % im2=insert_patches_Get_patches_2_lex(X,R,C,ps);
% % %
% % time_extraction_insertion=toc
% % figure,imshow(im2)

**Comment by ashkan-abbasi66** [comment]
Actually I should have removed these comments because they are some hints for me. You do not need the function `insert_patches_lex` since it is equivalent to another function named `insert_patches_Get_patches_2_lex` which is already in the package now.  As I remember, I replaced the former with the latter one because of its efficiency. However, If you want those functions, I will send them for you.

**Comment by scao7** [comment]
Thanks,
I have fixed the problem by replacing `insert_patches_lex` function with `insert_patches_Get_patches_2_lex` function. 
In the `demo_train_dictionary.m `, there is another missing function `disp_patches`. Could you send that function to me? Appreciate.

**Comment by ashkan-abbasi66** [comment]
I have uploaded the `disp_patches` function. You can download it now.
Regards,
Ashkan.

**Comment by scao7** [comment]
Thanks.
